language: generic
sudo: false
dist: trusty

notifications:
  email: false

script:
  - wc -m theories/*.v || echo -n ''
  - grep -E '^................................................................................' theories/*.v || echo -n ''
  - echo 'Good Job!'
